##spring.datasource.url=jdbc:mysql://host.docker.internal:3306/clubmanagement
##spring.datasource.username=root
##spring.datasource.password=
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##
### =========================
### = JPA CONFIGURATION     =
### =========================
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## ===============================
## APPLICATION
## ===============================
#spring.application.name=clubmanagement
#server.port=8080
#
## ===============================
## DATABASE (XAMPP MYSQL - LOCAL)
## ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/clubmanagement
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ===============================
## JPA / HIBERNATE
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## ===============================
## THYMELEAF
## ===============================
#spring.thymeleaf.cache=false

# ===============================
# APPLICATION
# ===============================

spring.application.name=clubmanagement

server.port=${PORT:8080}




spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/clubmanagement}

spring.datasource.username=${MYSQLUSER:root}

spring.datasource.password=${MYSQLPASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




spring.thymeleaf.cache=false
